wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.40.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1733309740
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 7
      - 13
      - 23
      - 66
      4: 3.9.19
      5: 0.17.4
      6: 4.40.2
      8:
      - 5
      9:
        1: transformers_trainer
      13: linux-x86_64
    m:
    - 1: train/global_step
      6:
      - 3
return_dict:
  desc: null
  value: true
output_hidden_states:
  desc: null
  value: false
output_attentions:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
torch_dtype:
  desc: null
  value: null
use_bfloat16:
  desc: null
  value: false
tf_legacy_loss:
  desc: null
  value: false
pruned_heads:
  desc: null
  value: {}
tie_word_embeddings:
  desc: null
  value: true
chunk_size_feed_forward:
  desc: null
  value: 0
is_encoder_decoder:
  desc: null
  value: true
is_decoder:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: true
tie_encoder_decoder:
  desc: null
  value: false
max_length:
  desc: null
  value: 20
min_length:
  desc: null
  value: 0
do_sample:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
num_beams:
  desc: null
  value: 1
num_beam_groups:
  desc: null
  value: 1
diversity_penalty:
  desc: null
  value: 0.0
temperature:
  desc: null
  value: 1.0
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
typical_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_penalty:
  desc: null
  value: 1.0
no_repeat_ngram_size:
  desc: null
  value: 0
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
bad_words_ids:
  desc: null
  value: null
num_return_sequences:
  desc: null
  value: 1
output_scores:
  desc: null
  value: false
return_dict_in_generate:
  desc: null
  value: false
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
remove_invalid_values:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
architectures:
  desc: null
  value: null
finetuning_task:
  desc: null
  value: null
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
tokenizer_class:
  desc: null
  value: null
prefix:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: null
pad_token_id:
  desc: null
  value: 1
eos_token_id:
  desc: null
  value: 0
sep_token_id:
  desc: null
  value: null
decoder_start_token_id:
  desc: null
  value: 0
task_specific_params:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
_name_or_path:
  desc: null
  value: ''
transformers_version:
  desc: null
  value: 4.40.2
encoder:
  desc: null
  value:
    return_dict: true
    output_hidden_states: false
    output_attentions: false
    torchscript: false
    torch_dtype: float32
    use_bfloat16: false
    tf_legacy_loss: false
    pruned_heads: {}
    tie_word_embeddings: true
    chunk_size_feed_forward: 0
    is_encoder_decoder: false
    is_decoder: false
    cross_attention_hidden_size: null
    add_cross_attention: false
    tie_encoder_decoder: false
    max_length: 512
    min_length: 0
    do_sample: false
    early_stopping: false
    num_beams: 1
    num_beam_groups: 1
    diversity_penalty: 0.0
    temperature: 1.0
    top_k: 50
    top_p: 1.0
    typical_p: 1.0
    repetition_penalty: 1.0
    length_penalty: 1.0
    no_repeat_ngram_size: 0
    encoder_no_repeat_ngram_size: 0
    bad_words_ids: null
    num_return_sequences: 1
    output_scores: false
    return_dict_in_generate: false
    forced_bos_token_id: null
    forced_eos_token_id: null
    remove_invalid_values: false
    exponential_decay_length_penalty: null
    suppress_tokens: null
    begin_suppress_tokens: null
    architectures:
    - RobertaForMaskedLM
    finetuning_task: null
    id2label:
      '0': LABEL_0
      '1': LABEL_1
    label2id:
      LABEL_0: 0
      LABEL_1: 1
    tokenizer_class: null
    prefix: null
    bos_token_id: 0
    pad_token_id: 1
    eos_token_id: 2
    sep_token_id: null
    decoder_start_token_id: null
    task_specific_params: null
    problem_type: null
    _name_or_path: /ibmm_data2/oas_database/paired_lea_tmp/heavy_model/src/redo_ch/FULL_config_4_smaller_model_run_lr5e-5_500epochs_max_seq_length_512/checkpoint-117674391
    max_seq_length: 512
    vocab_size: 25
    hidden_size: 512
    num_hidden_layers: 4
    num_attention_heads: 4
    hidden_act: gelu
    intermediate_size: 2048
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    max_position_embeddings: 514
    type_vocab_size: 1
    initializer_range: 0.02
    layer_norm_eps: 1.0e-05
    position_embedding_type: absolute
    use_cache: true
    classifier_dropout: null
    model_type: roberta
decoder:
  desc: null
  value:
    vocab_size: 23
    n_positions: 1024
    n_embd: 768
    n_layer: 12
    n_head: 12
    n_inner: null
    activation_function: gelu_new
    resid_pdrop: 0.1
    embd_pdrop: 0.1
    attn_pdrop: 0.1
    layer_norm_epsilon: 1.0e-05
    initializer_range: 0.02
    summary_type: cls_index
    summary_use_proj: true
    summary_activation: null
    summary_first_dropout: 0.1
    summary_proj_to_labels: true
    scale_attn_weights: true
    use_cache: true
    scale_attn_by_inverse_layer_idx: false
    reorder_and_upcast_attn: false
    bos_token_id: 0
    eos_token_id: 0
    return_dict: true
    output_hidden_states: false
    output_attentions: false
    torchscript: false
    torch_dtype: float32
    use_bfloat16: false
    tf_legacy_loss: false
    pruned_heads: {}
    tie_word_embeddings: true
    chunk_size_feed_forward: 0
    is_encoder_decoder: false
    is_decoder: true
    cross_attention_hidden_size: null
    add_cross_attention: true
    tie_encoder_decoder: false
    max_length: 20
    min_length: 0
    do_sample: false
    early_stopping: false
    num_beams: 1
    num_beam_groups: 1
    diversity_penalty: 0.0
    temperature: 1.0
    top_k: 50
    top_p: 1.0
    typical_p: 1.0
    repetition_penalty: 1.0
    length_penalty: 1.0
    no_repeat_ngram_size: 0
    encoder_no_repeat_ngram_size: 0
    bad_words_ids: null
    num_return_sequences: 1
    output_scores: false
    return_dict_in_generate: false
    forced_bos_token_id: null
    forced_eos_token_id: null
    remove_invalid_values: false
    exponential_decay_length_penalty: null
    suppress_tokens: null
    begin_suppress_tokens: null
    architectures:
    - GPT2LMHeadModel
    finetuning_task: null
    id2label:
      '0': LABEL_0
      '1': LABEL_1
    label2id:
      LABEL_0: 0
      LABEL_1: 1
    tokenizer_class: null
    prefix: null
    pad_token_id: 1
    sep_token_id: null
    decoder_start_token_id: null
    task_specific_params: null
    problem_type: null
    _name_or_path: /ibmm_data2/oas_database/paired_lea_tmp/paired_model/BERT2GPT/gpt_decoder/checkpoint-74
    n_ctx: 1024
    unk_token_id: 2
    model_type: gpt2
model_type:
  desc: null
  value: encoder-decoder
output_dir:
  desc: null
  value: /ibmm_data2/oas_database/paired_lea_tmp/paired_model/BERT2GPT/model_checkpoints/bert2gpt_DoLa_layers_high_rep_penal_1.2_full_PLAbDab_healthy_human_max_length_120_num_epochs_30_3
overwrite_output_dir:
  desc: null
  value: false
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: epoch
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 64
per_device_eval_batch_size:
  desc: null
  value: 64
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.1
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 30
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: linear
lr_scheduler_kwargs:
  desc: null
  value: {}
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: /ibmm_data2/oas_database/paired_lea_tmp/paired_model/BERT2GPT/model_checkpoints/bert2gpt_DoLa_layers_high_rep_penal_1.2_full_PLAbDab_healthy_human_max_length_120_num_epochs_30_3_logging
logging_strategy:
  desc: null
  value: epoch
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: epoch
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: null
save_safetensors:
  desc: null
  value: true
save_on_each_node:
  desc: null
  value: false
save_only_model:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_cpu:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: null
local_rank:
  desc: null
  value: 0
ddp_backend:
  desc: null
  value: null
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 0
dataloader_prefetch_factor:
  desc: null
  value: null
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: bert2gpt_DoLa_layers_high_rep_penal_1.2_full_PLAbDab_healthy_human_max_length_120_num_epochs_30_3
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
fsdp:
  desc: null
  value: []
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_v2: false
    xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
accelerator_config:
  desc: null
  value:
    split_batches: false
    dispatch_batches: null
    even_batches: true
    use_seedable_sampler: true
    gradient_accumulation_kwargs: null
deepspeed:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: adamw_torch
optim_args:
  desc: null
  value: null
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - wandb
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
dataloader_persistent_workers:
  desc: null
  value: false
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: false
hub_always_push:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: false
gradient_checkpointing_kwargs:
  desc: null
  value: null
include_inputs_for_metrics:
  desc: null
  value: false
eval_do_concat_batches:
  desc: null
  value: true
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
dispatch_batches:
  desc: null
  value: null
split_batches:
  desc: null
  value: null
include_tokens_per_second:
  desc: null
  value: false
include_num_input_tokens_seen:
  desc: null
  value: false
neftune_noise_alpha:
  desc: null
  value: null
optim_target_modules:
  desc: null
  value: null
sortish_sampler:
  desc: null
  value: false
predict_with_generate:
  desc: null
  value: true
generation_max_length:
  desc: null
  value: null
generation_num_beams:
  desc: null
  value: null
generation_config:
  desc: null
  value:
    max_length: 120
    max_new_tokens: null
    min_length: 50
    min_new_tokens: null
    early_stopping: false
    max_time: null
    do_sample: false
    num_beams: 1
    num_beam_groups: 1
    penalty_alpha: null
    use_cache: true
    temperature: 1.0
    top_k: 50
    top_p: 1.0
    typical_p: 1.0
    epsilon_cutoff: 0.0
    eta_cutoff: 0.0
    diversity_penalty: 0.0
    repetition_penalty: 1.0
    encoder_repetition_penalty: 1.0
    length_penalty: 1.0
    no_repeat_ngram_size: 0
    bad_words_ids: null
    force_words_ids: null
    renormalize_logits: false
    constraints: null
    forced_bos_token_id: null
    forced_eos_token_id: null
    remove_invalid_values: false
    exponential_decay_length_penalty: null
    suppress_tokens: null
    begin_suppress_tokens: null
    forced_decoder_ids: null
    sequence_bias: null
    guidance_scale: null
    low_memory: null
    num_return_sequences: 1
    output_attentions: false
    output_hidden_states: true
    output_scores: true
    output_logits: null
    return_dict_in_generate: true
    pad_token_id: 1
    bos_token_id: null
    eos_token_id: 0
    encoder_no_repeat_ngram_size: 0
    decoder_start_token_id: 0
    num_assistant_tokens: 5
    num_assistant_tokens_schedule: heuristic
    cache_implementation: null
    prompt_lookup_num_tokens: null
    max_matching_ngram_size: null
    generation_kwargs: {}
    _from_model_config: false
    transformers_version: 4.40.2
